### PR TITLE
Wifi only upload

### PR DESCRIPTION
**Pull request by stevenolen**
a basic implementation for #655.

Details of implementation:
  * New base entity (UserPreferences)
    * generically implemented as this could be useful for other things down the road.
    * offers a getter and setter method for an arbitrary preference
    * Defaults of these preferences can/should be specific in config files
    * Persists user changes to localstorage so they survive app death.
  * Added row to profile page for wifi-upload-only preference
    * rough css, Profile page still has some rudimentary styling so I didn't go overboard on this..
    * copied switch css from reminder page (noted that this could be abstracted, but I'm terrible at CSS and know nothing about blocks...so it's probably best if I don't do this).
    * toggling switch sets the preference (OFF = normal state, ON = app will *not* upload when on cell network.
  * Set `if` block for `native && wifi-upload-only && on cell network` in uploader:new method.
    * Continue to allow user to "retry" even with this failure (existing code appears to assume this)
    * added upload failure state for `wifionly` to all upload contexts.
    * this preference is not available in the browser (profile page is disabled currently), so "preference" is ignored if in browser.

@ctrance -- this has yet to be tested on iOS as I don't have iOS device with a cell connection (and it's required for testing the feature, ha!). Could you test this with the builds labeled `ohmageX-steve` on https://apps.ohmage.org ? -- note that I haven't pulled in @wrenr's recent dashboard changes (and pull from his branch mid-implementation) so it's best to report issues only relating to:
  * profile page (displaying wifi switch, toggling switch)
  * survey uploads (both from survey context and upload queue context)
    * should always upload if on wifi as well as if on cell and preference is set to "off" (which is default)
    * should never upload if on cell network and preference is set to "on" (survey upload attempts and upload queue single survey attempts should provide info about the preference being on, "upload all attempts" currently do not specify errors.
  * Killing app should keep preference. 
  * Logging out should set back to default

### CODE REVIEW

**Comment by ctrance** [comment]
@stevenolen - Everything else is working good except when refreshing history/campaign/dashboard and installing campaign, the app uses cell data though the "wifi only" preference is on.

**Comment by stevenolen** [comment]
thanks for the fast testing @ctrance! you are correct about the other data usages, and that is intentional for the time being (the feature  is "wifi **upload** only" to try to be clear to the user).  It would be quite a bit of additional work to case out every data call, especially since many of them use an incredibly small amount of data.  At this point we're trying to feature match the existing native android app, which allowed this specific feature (would only upload surveys via wifi if user requested).

Thank you!

**Comment by ctrance** [comment]
@stevenolen - Got it! We're good then :)!

**Comment by wrenr** [comment]
I will integrate this pull request, but I must make some refactors to the added  functionality to keep this in line with the proper implementation structure throughout the app. Of note:

This functions correctly, the implementation does however break view encapsulation in the changes to `/profile/show/show_view.js.coffee`. The view should not fetch data from an outside Entity from inside its onRender method. The view's model is defined in the "profile:current" event handler of the Profile entity when the Controller is initialized, and this `get` event should happen there and added as a property of this model. To manipulate setting the value, the `change` event on the switch should be broadcast as a view change event that its controller listens for inside of the profile `show_controller`, then that event should be listened for in the `profile_app` base Module and execute an event that the profile:set entity. Also the `user:preferences:set` event should be a Command instead of Request since it is not returning a requested value, but executing a change on the contents of the User Preferences Entity.

**Pull request merged**
